logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 116.62.157.97
    port: 5672
    username: hmall
    password: admin123
    virtual-host: /hmall
    listener:
      simple:
        prefetch: 1