### 端口
server:
  port: 8081

spring:
  application:
    name: white
  datasource:
    url: jdbc:mysql://localhost:3306/white?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

### mybatis-plus逻辑删除配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


springdoc:
  swagger-ui:
    enabled: true
    ### 自定义路径，配置后自动跳转swagger地址——/swagger-ui/index.html
    path: /doc
# http://localhost:8081/swagger-ui/index.html
logging:
  level:
    com.white: debug
